//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Minor
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class databaseEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new databaseEntities object using the connection string found in the 'databaseEntities' section of the application configuration file.
        /// </summary>
        public databaseEntities() : base("name=databaseEntities", "databaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new databaseEntities object.
        /// </summary>
        public databaseEntities(string connectionString) : base(connectionString, "databaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new databaseEntities object.
        /// </summary>
        public databaseEntities(EntityConnection connection) : base(connection, "databaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<db_Karyawan> db_Karyawan
        {
            get
            {
                if ((_db_Karyawan == null))
                {
                    _db_Karyawan = base.CreateObjectSet<db_Karyawan>("db_Karyawan");
                }
                return _db_Karyawan;
            }
        }
        private ObjectSet<db_Karyawan> _db_Karyawan;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<db_Pelanggan> db_Pelanggan
        {
            get
            {
                if ((_db_Pelanggan == null))
                {
                    _db_Pelanggan = base.CreateObjectSet<db_Pelanggan>("db_Pelanggan");
                }
                return _db_Pelanggan;
            }
        }
        private ObjectSet<db_Pelanggan> _db_Pelanggan;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<db_Detail_Form_Penjualan_Eceran> db_Detail_Form_Penjualan_Eceran
        {
            get
            {
                if ((_db_Detail_Form_Penjualan_Eceran == null))
                {
                    _db_Detail_Form_Penjualan_Eceran = base.CreateObjectSet<db_Detail_Form_Penjualan_Eceran>("db_Detail_Form_Penjualan_Eceran");
                }
                return _db_Detail_Form_Penjualan_Eceran;
            }
        }
        private ObjectSet<db_Detail_Form_Penjualan_Eceran> _db_Detail_Form_Penjualan_Eceran;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<db_Detail_Form_Penjualan_Grosir> db_Detail_Form_Penjualan_Grosir
        {
            get
            {
                if ((_db_Detail_Form_Penjualan_Grosir == null))
                {
                    _db_Detail_Form_Penjualan_Grosir = base.CreateObjectSet<db_Detail_Form_Penjualan_Grosir>("db_Detail_Form_Penjualan_Grosir");
                }
                return _db_Detail_Form_Penjualan_Grosir;
            }
        }
        private ObjectSet<db_Detail_Form_Penjualan_Grosir> _db_Detail_Form_Penjualan_Grosir;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<db_Detail_Retur_Pembelian> db_Detail_Retur_Pembelian
        {
            get
            {
                if ((_db_Detail_Retur_Pembelian == null))
                {
                    _db_Detail_Retur_Pembelian = base.CreateObjectSet<db_Detail_Retur_Pembelian>("db_Detail_Retur_Pembelian");
                }
                return _db_Detail_Retur_Pembelian;
            }
        }
        private ObjectSet<db_Detail_Retur_Pembelian> _db_Detail_Retur_Pembelian;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<db_Detail_Retur_Penjualan> db_Detail_Retur_Penjualan
        {
            get
            {
                if ((_db_Detail_Retur_Penjualan == null))
                {
                    _db_Detail_Retur_Penjualan = base.CreateObjectSet<db_Detail_Retur_Penjualan>("db_Detail_Retur_Penjualan");
                }
                return _db_Detail_Retur_Penjualan;
            }
        }
        private ObjectSet<db_Detail_Retur_Penjualan> _db_Detail_Retur_Penjualan;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<db_Detail_Faktur_Pemesanan> db_Detail_Faktur_Pemesanan
        {
            get
            {
                if ((_db_Detail_Faktur_Pemesanan == null))
                {
                    _db_Detail_Faktur_Pemesanan = base.CreateObjectSet<db_Detail_Faktur_Pemesanan>("db_Detail_Faktur_Pemesanan");
                }
                return _db_Detail_Faktur_Pemesanan;
            }
        }
        private ObjectSet<db_Detail_Faktur_Pemesanan> _db_Detail_Faktur_Pemesanan;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<db_Faktur_Pemesanan> db_Faktur_Pemesanan
        {
            get
            {
                if ((_db_Faktur_Pemesanan == null))
                {
                    _db_Faktur_Pemesanan = base.CreateObjectSet<db_Faktur_Pemesanan>("db_Faktur_Pemesanan");
                }
                return _db_Faktur_Pemesanan;
            }
        }
        private ObjectSet<db_Faktur_Pemesanan> _db_Faktur_Pemesanan;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<db_Form_Penjualan_Eceran> db_Form_Penjualan_Eceran
        {
            get
            {
                if ((_db_Form_Penjualan_Eceran == null))
                {
                    _db_Form_Penjualan_Eceran = base.CreateObjectSet<db_Form_Penjualan_Eceran>("db_Form_Penjualan_Eceran");
                }
                return _db_Form_Penjualan_Eceran;
            }
        }
        private ObjectSet<db_Form_Penjualan_Eceran> _db_Form_Penjualan_Eceran;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<db_Form_Penjualan_Grosir> db_Form_Penjualan_Grosir
        {
            get
            {
                if ((_db_Form_Penjualan_Grosir == null))
                {
                    _db_Form_Penjualan_Grosir = base.CreateObjectSet<db_Form_Penjualan_Grosir>("db_Form_Penjualan_Grosir");
                }
                return _db_Form_Penjualan_Grosir;
            }
        }
        private ObjectSet<db_Form_Penjualan_Grosir> _db_Form_Penjualan_Grosir;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<db_Retur_Pembelian> db_Retur_Pembelian
        {
            get
            {
                if ((_db_Retur_Pembelian == null))
                {
                    _db_Retur_Pembelian = base.CreateObjectSet<db_Retur_Pembelian>("db_Retur_Pembelian");
                }
                return _db_Retur_Pembelian;
            }
        }
        private ObjectSet<db_Retur_Pembelian> _db_Retur_Pembelian;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<db_Retur_Penjualan> db_Retur_Penjualan
        {
            get
            {
                if ((_db_Retur_Penjualan == null))
                {
                    _db_Retur_Penjualan = base.CreateObjectSet<db_Retur_Penjualan>("db_Retur_Penjualan");
                }
                return _db_Retur_Penjualan;
            }
        }
        private ObjectSet<db_Retur_Penjualan> _db_Retur_Penjualan;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<db_Supplier> db_Supplier
        {
            get
            {
                if ((_db_Supplier == null))
                {
                    _db_Supplier = base.CreateObjectSet<db_Supplier>("db_Supplier");
                }
                return _db_Supplier;
            }
        }
        private ObjectSet<db_Supplier> _db_Supplier;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<db_Barang> db_Barang
        {
            get
            {
                if ((_db_Barang == null))
                {
                    _db_Barang = base.CreateObjectSet<db_Barang>("db_Barang");
                }
                return _db_Barang;
            }
        }
        private ObjectSet<db_Barang> _db_Barang;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the db_Karyawan EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodb_Karyawan(db_Karyawan db_Karyawan)
        {
            base.AddObject("db_Karyawan", db_Karyawan);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the db_Pelanggan EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodb_Pelanggan(db_Pelanggan db_Pelanggan)
        {
            base.AddObject("db_Pelanggan", db_Pelanggan);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the db_Detail_Form_Penjualan_Eceran EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodb_Detail_Form_Penjualan_Eceran(db_Detail_Form_Penjualan_Eceran db_Detail_Form_Penjualan_Eceran)
        {
            base.AddObject("db_Detail_Form_Penjualan_Eceran", db_Detail_Form_Penjualan_Eceran);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the db_Detail_Form_Penjualan_Grosir EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodb_Detail_Form_Penjualan_Grosir(db_Detail_Form_Penjualan_Grosir db_Detail_Form_Penjualan_Grosir)
        {
            base.AddObject("db_Detail_Form_Penjualan_Grosir", db_Detail_Form_Penjualan_Grosir);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the db_Detail_Retur_Pembelian EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodb_Detail_Retur_Pembelian(db_Detail_Retur_Pembelian db_Detail_Retur_Pembelian)
        {
            base.AddObject("db_Detail_Retur_Pembelian", db_Detail_Retur_Pembelian);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the db_Detail_Retur_Penjualan EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodb_Detail_Retur_Penjualan(db_Detail_Retur_Penjualan db_Detail_Retur_Penjualan)
        {
            base.AddObject("db_Detail_Retur_Penjualan", db_Detail_Retur_Penjualan);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the db_Detail_Faktur_Pemesanan EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodb_Detail_Faktur_Pemesanan(db_Detail_Faktur_Pemesanan db_Detail_Faktur_Pemesanan)
        {
            base.AddObject("db_Detail_Faktur_Pemesanan", db_Detail_Faktur_Pemesanan);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the db_Faktur_Pemesanan EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodb_Faktur_Pemesanan(db_Faktur_Pemesanan db_Faktur_Pemesanan)
        {
            base.AddObject("db_Faktur_Pemesanan", db_Faktur_Pemesanan);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the db_Form_Penjualan_Eceran EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodb_Form_Penjualan_Eceran(db_Form_Penjualan_Eceran db_Form_Penjualan_Eceran)
        {
            base.AddObject("db_Form_Penjualan_Eceran", db_Form_Penjualan_Eceran);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the db_Form_Penjualan_Grosir EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodb_Form_Penjualan_Grosir(db_Form_Penjualan_Grosir db_Form_Penjualan_Grosir)
        {
            base.AddObject("db_Form_Penjualan_Grosir", db_Form_Penjualan_Grosir);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the db_Retur_Pembelian EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodb_Retur_Pembelian(db_Retur_Pembelian db_Retur_Pembelian)
        {
            base.AddObject("db_Retur_Pembelian", db_Retur_Pembelian);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the db_Retur_Penjualan EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodb_Retur_Penjualan(db_Retur_Penjualan db_Retur_Penjualan)
        {
            base.AddObject("db_Retur_Penjualan", db_Retur_Penjualan);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the db_Supplier EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodb_Supplier(db_Supplier db_Supplier)
        {
            base.AddObject("db_Supplier", db_Supplier);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the db_Barang EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodb_Barang(db_Barang db_Barang)
        {
            base.AddObject("db_Barang", db_Barang);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="databaseModel", Name="db_Barang")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class db_Barang : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new db_Barang object.
        /// </summary>
        /// <param name="iD_Barang">Initial value of the ID_Barang property.</param>
        public static db_Barang Createdb_Barang(global::System.String iD_Barang)
        {
            db_Barang db_Barang = new db_Barang();
            db_Barang.ID_Barang = iD_Barang;
            return db_Barang;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID_Barang
        {
            get
            {
                return _ID_Barang;
            }
            set
            {
                if (_ID_Barang != value)
                {
                    OnID_BarangChanging(value);
                    ReportPropertyChanging("ID_Barang");
                    _ID_Barang = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ID_Barang");
                    OnID_BarangChanged();
                }
            }
        }
        private global::System.String _ID_Barang;
        partial void OnID_BarangChanging(global::System.String value);
        partial void OnID_BarangChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nama_Barang
        {
            get
            {
                return _Nama_Barang;
            }
            set
            {
                OnNama_BarangChanging(value);
                ReportPropertyChanging("Nama_Barang");
                _Nama_Barang = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nama_Barang");
                OnNama_BarangChanged();
            }
        }
        private global::System.String _Nama_Barang;
        partial void OnNama_BarangChanging(global::System.String value);
        partial void OnNama_BarangChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Jenis_Barang
        {
            get
            {
                return _Jenis_Barang;
            }
            set
            {
                OnJenis_BarangChanging(value);
                ReportPropertyChanging("Jenis_Barang");
                _Jenis_Barang = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Jenis_Barang");
                OnJenis_BarangChanged();
            }
        }
        private global::System.String _Jenis_Barang;
        partial void OnJenis_BarangChanging(global::System.String value);
        partial void OnJenis_BarangChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Harga_Beli
        {
            get
            {
                return _Harga_Beli;
            }
            set
            {
                OnHarga_BeliChanging(value);
                ReportPropertyChanging("Harga_Beli");
                _Harga_Beli = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Harga_Beli");
                OnHarga_BeliChanged();
            }
        }
        private Nullable<global::System.Int32> _Harga_Beli;
        partial void OnHarga_BeliChanging(Nullable<global::System.Int32> value);
        partial void OnHarga_BeliChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Harga_Jual
        {
            get
            {
                return _Harga_Jual;
            }
            set
            {
                OnHarga_JualChanging(value);
                ReportPropertyChanging("Harga_Jual");
                _Harga_Jual = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Harga_Jual");
                OnHarga_JualChanged();
            }
        }
        private Nullable<global::System.Int32> _Harga_Jual;
        partial void OnHarga_JualChanging(Nullable<global::System.Int32> value);
        partial void OnHarga_JualChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Harga_Member
        {
            get
            {
                return _Harga_Member;
            }
            set
            {
                OnHarga_MemberChanging(value);
                ReportPropertyChanging("Harga_Member");
                _Harga_Member = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Harga_Member");
                OnHarga_MemberChanged();
            }
        }
        private Nullable<global::System.Int32> _Harga_Member;
        partial void OnHarga_MemberChanging(Nullable<global::System.Int32> value);
        partial void OnHarga_MemberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Stock
        {
            get
            {
                return _Stock;
            }
            set
            {
                OnStockChanging(value);
                ReportPropertyChanging("Stock");
                _Stock = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Stock");
                OnStockChanged();
            }
        }
        private Nullable<global::System.Int32> _Stock;
        partial void OnStockChanging(Nullable<global::System.Int32> value);
        partial void OnStockChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ID_Supplier
        {
            get
            {
                return _ID_Supplier;
            }
            set
            {
                OnID_SupplierChanging(value);
                ReportPropertyChanging("ID_Supplier");
                _ID_Supplier = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ID_Supplier");
                OnID_SupplierChanged();
            }
        }
        private global::System.String _ID_Supplier;
        partial void OnID_SupplierChanging(global::System.String value);
        partial void OnID_SupplierChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="databaseModel", Name="db_Detail_Faktur_Pemesanan")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class db_Detail_Faktur_Pemesanan : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new db_Detail_Faktur_Pemesanan object.
        /// </summary>
        /// <param name="no_Faktur_Pemesanan">Initial value of the No_Faktur_Pemesanan property.</param>
        /// <param name="iD_Barang">Initial value of the ID_Barang property.</param>
        public static db_Detail_Faktur_Pemesanan Createdb_Detail_Faktur_Pemesanan(global::System.String no_Faktur_Pemesanan, global::System.String iD_Barang)
        {
            db_Detail_Faktur_Pemesanan db_Detail_Faktur_Pemesanan = new db_Detail_Faktur_Pemesanan();
            db_Detail_Faktur_Pemesanan.No_Faktur_Pemesanan = no_Faktur_Pemesanan;
            db_Detail_Faktur_Pemesanan.ID_Barang = iD_Barang;
            return db_Detail_Faktur_Pemesanan;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String No_Faktur_Pemesanan
        {
            get
            {
                return _No_Faktur_Pemesanan;
            }
            set
            {
                if (_No_Faktur_Pemesanan != value)
                {
                    OnNo_Faktur_PemesananChanging(value);
                    ReportPropertyChanging("No_Faktur_Pemesanan");
                    _No_Faktur_Pemesanan = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("No_Faktur_Pemesanan");
                    OnNo_Faktur_PemesananChanged();
                }
            }
        }
        private global::System.String _No_Faktur_Pemesanan;
        partial void OnNo_Faktur_PemesananChanging(global::System.String value);
        partial void OnNo_Faktur_PemesananChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID_Barang
        {
            get
            {
                return _ID_Barang;
            }
            set
            {
                if (_ID_Barang != value)
                {
                    OnID_BarangChanging(value);
                    ReportPropertyChanging("ID_Barang");
                    _ID_Barang = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ID_Barang");
                    OnID_BarangChanged();
                }
            }
        }
        private global::System.String _ID_Barang;
        partial void OnID_BarangChanging(global::System.String value);
        partial void OnID_BarangChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Jumlah
        {
            get
            {
                return _Jumlah;
            }
            set
            {
                OnJumlahChanging(value);
                ReportPropertyChanging("Jumlah");
                _Jumlah = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Jumlah");
                OnJumlahChanged();
            }
        }
        private Nullable<global::System.Int32> _Jumlah;
        partial void OnJumlahChanging(Nullable<global::System.Int32> value);
        partial void OnJumlahChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nama_Barang
        {
            get
            {
                return _Nama_Barang;
            }
            set
            {
                OnNama_BarangChanging(value);
                ReportPropertyChanging("Nama_Barang");
                _Nama_Barang = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nama_Barang");
                OnNama_BarangChanged();
            }
        }
        private global::System.String _Nama_Barang;
        partial void OnNama_BarangChanging(global::System.String value);
        partial void OnNama_BarangChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Harga
        {
            get
            {
                return _Harga;
            }
            set
            {
                OnHargaChanging(value);
                ReportPropertyChanging("Harga");
                _Harga = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Harga");
                OnHargaChanged();
            }
        }
        private Nullable<global::System.Int32> _Harga;
        partial void OnHargaChanging(Nullable<global::System.Int32> value);
        partial void OnHargaChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="databaseModel", Name="db_Detail_Form_Penjualan_Eceran")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class db_Detail_Form_Penjualan_Eceran : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new db_Detail_Form_Penjualan_Eceran object.
        /// </summary>
        /// <param name="no_Form_Penjualan_Eceran">Initial value of the No_Form_Penjualan_Eceran property.</param>
        /// <param name="iD_Barang">Initial value of the ID_Barang property.</param>
        public static db_Detail_Form_Penjualan_Eceran Createdb_Detail_Form_Penjualan_Eceran(global::System.String no_Form_Penjualan_Eceran, global::System.String iD_Barang)
        {
            db_Detail_Form_Penjualan_Eceran db_Detail_Form_Penjualan_Eceran = new db_Detail_Form_Penjualan_Eceran();
            db_Detail_Form_Penjualan_Eceran.No_Form_Penjualan_Eceran = no_Form_Penjualan_Eceran;
            db_Detail_Form_Penjualan_Eceran.ID_Barang = iD_Barang;
            return db_Detail_Form_Penjualan_Eceran;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String No_Form_Penjualan_Eceran
        {
            get
            {
                return _No_Form_Penjualan_Eceran;
            }
            set
            {
                if (_No_Form_Penjualan_Eceran != value)
                {
                    OnNo_Form_Penjualan_EceranChanging(value);
                    ReportPropertyChanging("No_Form_Penjualan_Eceran");
                    _No_Form_Penjualan_Eceran = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("No_Form_Penjualan_Eceran");
                    OnNo_Form_Penjualan_EceranChanged();
                }
            }
        }
        private global::System.String _No_Form_Penjualan_Eceran;
        partial void OnNo_Form_Penjualan_EceranChanging(global::System.String value);
        partial void OnNo_Form_Penjualan_EceranChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID_Barang
        {
            get
            {
                return _ID_Barang;
            }
            set
            {
                if (_ID_Barang != value)
                {
                    OnID_BarangChanging(value);
                    ReportPropertyChanging("ID_Barang");
                    _ID_Barang = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ID_Barang");
                    OnID_BarangChanged();
                }
            }
        }
        private global::System.String _ID_Barang;
        partial void OnID_BarangChanging(global::System.String value);
        partial void OnID_BarangChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Harga
        {
            get
            {
                return _Harga;
            }
            set
            {
                OnHargaChanging(value);
                ReportPropertyChanging("Harga");
                _Harga = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Harga");
                OnHargaChanged();
            }
        }
        private Nullable<global::System.Int32> _Harga;
        partial void OnHargaChanging(Nullable<global::System.Int32> value);
        partial void OnHargaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Jumlah
        {
            get
            {
                return _Jumlah;
            }
            set
            {
                OnJumlahChanging(value);
                ReportPropertyChanging("Jumlah");
                _Jumlah = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Jumlah");
                OnJumlahChanged();
            }
        }
        private Nullable<global::System.Int32> _Jumlah;
        partial void OnJumlahChanging(Nullable<global::System.Int32> value);
        partial void OnJumlahChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nama_Barang
        {
            get
            {
                return _Nama_Barang;
            }
            set
            {
                OnNama_BarangChanging(value);
                ReportPropertyChanging("Nama_Barang");
                _Nama_Barang = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nama_Barang");
                OnNama_BarangChanged();
            }
        }
        private global::System.String _Nama_Barang;
        partial void OnNama_BarangChanging(global::System.String value);
        partial void OnNama_BarangChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="databaseModel", Name="db_Detail_Form_Penjualan_Grosir")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class db_Detail_Form_Penjualan_Grosir : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new db_Detail_Form_Penjualan_Grosir object.
        /// </summary>
        /// <param name="no_Form_Penjualan_Grosir">Initial value of the No_Form_Penjualan_Grosir property.</param>
        /// <param name="iD_Barang">Initial value of the ID_Barang property.</param>
        public static db_Detail_Form_Penjualan_Grosir Createdb_Detail_Form_Penjualan_Grosir(global::System.String no_Form_Penjualan_Grosir, global::System.String iD_Barang)
        {
            db_Detail_Form_Penjualan_Grosir db_Detail_Form_Penjualan_Grosir = new db_Detail_Form_Penjualan_Grosir();
            db_Detail_Form_Penjualan_Grosir.No_Form_Penjualan_Grosir = no_Form_Penjualan_Grosir;
            db_Detail_Form_Penjualan_Grosir.ID_Barang = iD_Barang;
            return db_Detail_Form_Penjualan_Grosir;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String No_Form_Penjualan_Grosir
        {
            get
            {
                return _No_Form_Penjualan_Grosir;
            }
            set
            {
                if (_No_Form_Penjualan_Grosir != value)
                {
                    OnNo_Form_Penjualan_GrosirChanging(value);
                    ReportPropertyChanging("No_Form_Penjualan_Grosir");
                    _No_Form_Penjualan_Grosir = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("No_Form_Penjualan_Grosir");
                    OnNo_Form_Penjualan_GrosirChanged();
                }
            }
        }
        private global::System.String _No_Form_Penjualan_Grosir;
        partial void OnNo_Form_Penjualan_GrosirChanging(global::System.String value);
        partial void OnNo_Form_Penjualan_GrosirChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID_Barang
        {
            get
            {
                return _ID_Barang;
            }
            set
            {
                if (_ID_Barang != value)
                {
                    OnID_BarangChanging(value);
                    ReportPropertyChanging("ID_Barang");
                    _ID_Barang = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ID_Barang");
                    OnID_BarangChanged();
                }
            }
        }
        private global::System.String _ID_Barang;
        partial void OnID_BarangChanging(global::System.String value);
        partial void OnID_BarangChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Harga
        {
            get
            {
                return _Harga;
            }
            set
            {
                OnHargaChanging(value);
                ReportPropertyChanging("Harga");
                _Harga = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Harga");
                OnHargaChanged();
            }
        }
        private Nullable<global::System.Int32> _Harga;
        partial void OnHargaChanging(Nullable<global::System.Int32> value);
        partial void OnHargaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Jumlah
        {
            get
            {
                return _Jumlah;
            }
            set
            {
                OnJumlahChanging(value);
                ReportPropertyChanging("Jumlah");
                _Jumlah = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Jumlah");
                OnJumlahChanged();
            }
        }
        private Nullable<global::System.Int32> _Jumlah;
        partial void OnJumlahChanging(Nullable<global::System.Int32> value);
        partial void OnJumlahChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nama_Barang
        {
            get
            {
                return _Nama_Barang;
            }
            set
            {
                OnNama_BarangChanging(value);
                ReportPropertyChanging("Nama_Barang");
                _Nama_Barang = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nama_Barang");
                OnNama_BarangChanged();
            }
        }
        private global::System.String _Nama_Barang;
        partial void OnNama_BarangChanging(global::System.String value);
        partial void OnNama_BarangChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="databaseModel", Name="db_Detail_Retur_Pembelian")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class db_Detail_Retur_Pembelian : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new db_Detail_Retur_Pembelian object.
        /// </summary>
        /// <param name="no_Retur_Pembelian">Initial value of the No_Retur_Pembelian property.</param>
        /// <param name="iD_Barang">Initial value of the ID_Barang property.</param>
        public static db_Detail_Retur_Pembelian Createdb_Detail_Retur_Pembelian(global::System.String no_Retur_Pembelian, global::System.String iD_Barang)
        {
            db_Detail_Retur_Pembelian db_Detail_Retur_Pembelian = new db_Detail_Retur_Pembelian();
            db_Detail_Retur_Pembelian.No_Retur_Pembelian = no_Retur_Pembelian;
            db_Detail_Retur_Pembelian.ID_Barang = iD_Barang;
            return db_Detail_Retur_Pembelian;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String No_Retur_Pembelian
        {
            get
            {
                return _No_Retur_Pembelian;
            }
            set
            {
                if (_No_Retur_Pembelian != value)
                {
                    OnNo_Retur_PembelianChanging(value);
                    ReportPropertyChanging("No_Retur_Pembelian");
                    _No_Retur_Pembelian = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("No_Retur_Pembelian");
                    OnNo_Retur_PembelianChanged();
                }
            }
        }
        private global::System.String _No_Retur_Pembelian;
        partial void OnNo_Retur_PembelianChanging(global::System.String value);
        partial void OnNo_Retur_PembelianChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID_Barang
        {
            get
            {
                return _ID_Barang;
            }
            set
            {
                if (_ID_Barang != value)
                {
                    OnID_BarangChanging(value);
                    ReportPropertyChanging("ID_Barang");
                    _ID_Barang = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ID_Barang");
                    OnID_BarangChanged();
                }
            }
        }
        private global::System.String _ID_Barang;
        partial void OnID_BarangChanging(global::System.String value);
        partial void OnID_BarangChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Jumlah
        {
            get
            {
                return _Jumlah;
            }
            set
            {
                OnJumlahChanging(value);
                ReportPropertyChanging("Jumlah");
                _Jumlah = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Jumlah");
                OnJumlahChanged();
            }
        }
        private Nullable<global::System.Int32> _Jumlah;
        partial void OnJumlahChanging(Nullable<global::System.Int32> value);
        partial void OnJumlahChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Deskripsi
        {
            get
            {
                return _Deskripsi;
            }
            set
            {
                OnDeskripsiChanging(value);
                ReportPropertyChanging("Deskripsi");
                _Deskripsi = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Deskripsi");
                OnDeskripsiChanged();
            }
        }
        private global::System.String _Deskripsi;
        partial void OnDeskripsiChanging(global::System.String value);
        partial void OnDeskripsiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nama_Barang
        {
            get
            {
                return _Nama_Barang;
            }
            set
            {
                OnNama_BarangChanging(value);
                ReportPropertyChanging("Nama_Barang");
                _Nama_Barang = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nama_Barang");
                OnNama_BarangChanged();
            }
        }
        private global::System.String _Nama_Barang;
        partial void OnNama_BarangChanging(global::System.String value);
        partial void OnNama_BarangChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="databaseModel", Name="db_Detail_Retur_Penjualan")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class db_Detail_Retur_Penjualan : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new db_Detail_Retur_Penjualan object.
        /// </summary>
        /// <param name="no_Retur_Penjualan">Initial value of the No_Retur_Penjualan property.</param>
        /// <param name="iD_Barang">Initial value of the ID_Barang property.</param>
        public static db_Detail_Retur_Penjualan Createdb_Detail_Retur_Penjualan(global::System.String no_Retur_Penjualan, global::System.String iD_Barang)
        {
            db_Detail_Retur_Penjualan db_Detail_Retur_Penjualan = new db_Detail_Retur_Penjualan();
            db_Detail_Retur_Penjualan.No_Retur_Penjualan = no_Retur_Penjualan;
            db_Detail_Retur_Penjualan.ID_Barang = iD_Barang;
            return db_Detail_Retur_Penjualan;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String No_Retur_Penjualan
        {
            get
            {
                return _No_Retur_Penjualan;
            }
            set
            {
                if (_No_Retur_Penjualan != value)
                {
                    OnNo_Retur_PenjualanChanging(value);
                    ReportPropertyChanging("No_Retur_Penjualan");
                    _No_Retur_Penjualan = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("No_Retur_Penjualan");
                    OnNo_Retur_PenjualanChanged();
                }
            }
        }
        private global::System.String _No_Retur_Penjualan;
        partial void OnNo_Retur_PenjualanChanging(global::System.String value);
        partial void OnNo_Retur_PenjualanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID_Barang
        {
            get
            {
                return _ID_Barang;
            }
            set
            {
                if (_ID_Barang != value)
                {
                    OnID_BarangChanging(value);
                    ReportPropertyChanging("ID_Barang");
                    _ID_Barang = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ID_Barang");
                    OnID_BarangChanged();
                }
            }
        }
        private global::System.String _ID_Barang;
        partial void OnID_BarangChanging(global::System.String value);
        partial void OnID_BarangChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Jumlah
        {
            get
            {
                return _Jumlah;
            }
            set
            {
                OnJumlahChanging(value);
                ReportPropertyChanging("Jumlah");
                _Jumlah = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Jumlah");
                OnJumlahChanged();
            }
        }
        private Nullable<global::System.Int32> _Jumlah;
        partial void OnJumlahChanging(Nullable<global::System.Int32> value);
        partial void OnJumlahChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Deskripsi
        {
            get
            {
                return _Deskripsi;
            }
            set
            {
                OnDeskripsiChanging(value);
                ReportPropertyChanging("Deskripsi");
                _Deskripsi = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Deskripsi");
                OnDeskripsiChanged();
            }
        }
        private global::System.String _Deskripsi;
        partial void OnDeskripsiChanging(global::System.String value);
        partial void OnDeskripsiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nama_Barang
        {
            get
            {
                return _Nama_Barang;
            }
            set
            {
                OnNama_BarangChanging(value);
                ReportPropertyChanging("Nama_Barang");
                _Nama_Barang = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nama_Barang");
                OnNama_BarangChanged();
            }
        }
        private global::System.String _Nama_Barang;
        partial void OnNama_BarangChanging(global::System.String value);
        partial void OnNama_BarangChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="databaseModel", Name="db_Faktur_Pemesanan")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class db_Faktur_Pemesanan : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new db_Faktur_Pemesanan object.
        /// </summary>
        /// <param name="no_Faktur_Pemesanan">Initial value of the No_Faktur_Pemesanan property.</param>
        public static db_Faktur_Pemesanan Createdb_Faktur_Pemesanan(global::System.String no_Faktur_Pemesanan)
        {
            db_Faktur_Pemesanan db_Faktur_Pemesanan = new db_Faktur_Pemesanan();
            db_Faktur_Pemesanan.No_Faktur_Pemesanan = no_Faktur_Pemesanan;
            return db_Faktur_Pemesanan;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String No_Faktur_Pemesanan
        {
            get
            {
                return _No_Faktur_Pemesanan;
            }
            set
            {
                if (_No_Faktur_Pemesanan != value)
                {
                    OnNo_Faktur_PemesananChanging(value);
                    ReportPropertyChanging("No_Faktur_Pemesanan");
                    _No_Faktur_Pemesanan = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("No_Faktur_Pemesanan");
                    OnNo_Faktur_PemesananChanged();
                }
            }
        }
        private global::System.String _No_Faktur_Pemesanan;
        partial void OnNo_Faktur_PemesananChanging(global::System.String value);
        partial void OnNo_Faktur_PemesananChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ID_Karyawan
        {
            get
            {
                return _ID_Karyawan;
            }
            set
            {
                OnID_KaryawanChanging(value);
                ReportPropertyChanging("ID_Karyawan");
                _ID_Karyawan = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ID_Karyawan");
                OnID_KaryawanChanged();
            }
        }
        private global::System.String _ID_Karyawan;
        partial void OnID_KaryawanChanging(global::System.String value);
        partial void OnID_KaryawanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ID_Supplier
        {
            get
            {
                return _ID_Supplier;
            }
            set
            {
                OnID_SupplierChanging(value);
                ReportPropertyChanging("ID_Supplier");
                _ID_Supplier = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ID_Supplier");
                OnID_SupplierChanged();
            }
        }
        private global::System.String _ID_Supplier;
        partial void OnID_SupplierChanging(global::System.String value);
        partial void OnID_SupplierChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tanggal
        {
            get
            {
                return _Tanggal;
            }
            set
            {
                OnTanggalChanging(value);
                ReportPropertyChanging("Tanggal");
                _Tanggal = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tanggal");
                OnTanggalChanged();
            }
        }
        private global::System.String _Tanggal;
        partial void OnTanggalChanging(global::System.String value);
        partial void OnTanggalChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="databaseModel", Name="db_Form_Penjualan_Eceran")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class db_Form_Penjualan_Eceran : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new db_Form_Penjualan_Eceran object.
        /// </summary>
        /// <param name="no_Form_Penjualan_Eceran">Initial value of the No_Form_Penjualan_Eceran property.</param>
        public static db_Form_Penjualan_Eceran Createdb_Form_Penjualan_Eceran(global::System.String no_Form_Penjualan_Eceran)
        {
            db_Form_Penjualan_Eceran db_Form_Penjualan_Eceran = new db_Form_Penjualan_Eceran();
            db_Form_Penjualan_Eceran.No_Form_Penjualan_Eceran = no_Form_Penjualan_Eceran;
            return db_Form_Penjualan_Eceran;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String No_Form_Penjualan_Eceran
        {
            get
            {
                return _No_Form_Penjualan_Eceran;
            }
            set
            {
                if (_No_Form_Penjualan_Eceran != value)
                {
                    OnNo_Form_Penjualan_EceranChanging(value);
                    ReportPropertyChanging("No_Form_Penjualan_Eceran");
                    _No_Form_Penjualan_Eceran = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("No_Form_Penjualan_Eceran");
                    OnNo_Form_Penjualan_EceranChanged();
                }
            }
        }
        private global::System.String _No_Form_Penjualan_Eceran;
        partial void OnNo_Form_Penjualan_EceranChanging(global::System.String value);
        partial void OnNo_Form_Penjualan_EceranChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ID_Karyawan
        {
            get
            {
                return _ID_Karyawan;
            }
            set
            {
                OnID_KaryawanChanging(value);
                ReportPropertyChanging("ID_Karyawan");
                _ID_Karyawan = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ID_Karyawan");
                OnID_KaryawanChanged();
            }
        }
        private global::System.String _ID_Karyawan;
        partial void OnID_KaryawanChanging(global::System.String value);
        partial void OnID_KaryawanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tanggal
        {
            get
            {
                return _Tanggal;
            }
            set
            {
                OnTanggalChanging(value);
                ReportPropertyChanging("Tanggal");
                _Tanggal = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tanggal");
                OnTanggalChanged();
            }
        }
        private global::System.String _Tanggal;
        partial void OnTanggalChanging(global::System.String value);
        partial void OnTanggalChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="databaseModel", Name="db_Form_Penjualan_Grosir")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class db_Form_Penjualan_Grosir : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new db_Form_Penjualan_Grosir object.
        /// </summary>
        /// <param name="no_Form_Penjualan_Grosir">Initial value of the No_Form_Penjualan_Grosir property.</param>
        public static db_Form_Penjualan_Grosir Createdb_Form_Penjualan_Grosir(global::System.String no_Form_Penjualan_Grosir)
        {
            db_Form_Penjualan_Grosir db_Form_Penjualan_Grosir = new db_Form_Penjualan_Grosir();
            db_Form_Penjualan_Grosir.No_Form_Penjualan_Grosir = no_Form_Penjualan_Grosir;
            return db_Form_Penjualan_Grosir;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String No_Form_Penjualan_Grosir
        {
            get
            {
                return _No_Form_Penjualan_Grosir;
            }
            set
            {
                if (_No_Form_Penjualan_Grosir != value)
                {
                    OnNo_Form_Penjualan_GrosirChanging(value);
                    ReportPropertyChanging("No_Form_Penjualan_Grosir");
                    _No_Form_Penjualan_Grosir = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("No_Form_Penjualan_Grosir");
                    OnNo_Form_Penjualan_GrosirChanged();
                }
            }
        }
        private global::System.String _No_Form_Penjualan_Grosir;
        partial void OnNo_Form_Penjualan_GrosirChanging(global::System.String value);
        partial void OnNo_Form_Penjualan_GrosirChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ID_Karyawan
        {
            get
            {
                return _ID_Karyawan;
            }
            set
            {
                OnID_KaryawanChanging(value);
                ReportPropertyChanging("ID_Karyawan");
                _ID_Karyawan = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ID_Karyawan");
                OnID_KaryawanChanged();
            }
        }
        private global::System.String _ID_Karyawan;
        partial void OnID_KaryawanChanging(global::System.String value);
        partial void OnID_KaryawanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ID_Pelanggan
        {
            get
            {
                return _ID_Pelanggan;
            }
            set
            {
                OnID_PelangganChanging(value);
                ReportPropertyChanging("ID_Pelanggan");
                _ID_Pelanggan = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ID_Pelanggan");
                OnID_PelangganChanged();
            }
        }
        private global::System.String _ID_Pelanggan;
        partial void OnID_PelangganChanging(global::System.String value);
        partial void OnID_PelangganChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tanggal
        {
            get
            {
                return _Tanggal;
            }
            set
            {
                OnTanggalChanging(value);
                ReportPropertyChanging("Tanggal");
                _Tanggal = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tanggal");
                OnTanggalChanged();
            }
        }
        private global::System.String _Tanggal;
        partial void OnTanggalChanging(global::System.String value);
        partial void OnTanggalChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="databaseModel", Name="db_Karyawan")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class db_Karyawan : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new db_Karyawan object.
        /// </summary>
        /// <param name="iD_Karyawan">Initial value of the ID_Karyawan property.</param>
        public static db_Karyawan Createdb_Karyawan(global::System.String iD_Karyawan)
        {
            db_Karyawan db_Karyawan = new db_Karyawan();
            db_Karyawan.ID_Karyawan = iD_Karyawan;
            return db_Karyawan;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID_Karyawan
        {
            get
            {
                return _ID_Karyawan;
            }
            set
            {
                if (_ID_Karyawan != value)
                {
                    OnID_KaryawanChanging(value);
                    ReportPropertyChanging("ID_Karyawan");
                    _ID_Karyawan = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ID_Karyawan");
                    OnID_KaryawanChanged();
                }
            }
        }
        private global::System.String _ID_Karyawan;
        partial void OnID_KaryawanChanging(global::System.String value);
        partial void OnID_KaryawanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nama_Karyawan
        {
            get
            {
                return _Nama_Karyawan;
            }
            set
            {
                OnNama_KaryawanChanging(value);
                ReportPropertyChanging("Nama_Karyawan");
                _Nama_Karyawan = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nama_Karyawan");
                OnNama_KaryawanChanged();
            }
        }
        private global::System.String _Nama_Karyawan;
        partial void OnNama_KaryawanChanging(global::System.String value);
        partial void OnNama_KaryawanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Tanggal_Lahir_Karyawan
        {
            get
            {
                return _Tanggal_Lahir_Karyawan;
            }
            set
            {
                OnTanggal_Lahir_KaryawanChanging(value);
                ReportPropertyChanging("Tanggal_Lahir_Karyawan");
                _Tanggal_Lahir_Karyawan = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Tanggal_Lahir_Karyawan");
                OnTanggal_Lahir_KaryawanChanged();
            }
        }
        private Nullable<global::System.DateTime> _Tanggal_Lahir_Karyawan;
        partial void OnTanggal_Lahir_KaryawanChanging(Nullable<global::System.DateTime> value);
        partial void OnTanggal_Lahir_KaryawanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Jenis_Kelamin_Karyawan
        {
            get
            {
                return _Jenis_Kelamin_Karyawan;
            }
            set
            {
                OnJenis_Kelamin_KaryawanChanging(value);
                ReportPropertyChanging("Jenis_Kelamin_Karyawan");
                _Jenis_Kelamin_Karyawan = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Jenis_Kelamin_Karyawan");
                OnJenis_Kelamin_KaryawanChanged();
            }
        }
        private global::System.String _Jenis_Kelamin_Karyawan;
        partial void OnJenis_Kelamin_KaryawanChanging(global::System.String value);
        partial void OnJenis_Kelamin_KaryawanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String No_Telepon_Karyawan
        {
            get
            {
                return _No_Telepon_Karyawan;
            }
            set
            {
                OnNo_Telepon_KaryawanChanging(value);
                ReportPropertyChanging("No_Telepon_Karyawan");
                _No_Telepon_Karyawan = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("No_Telepon_Karyawan");
                OnNo_Telepon_KaryawanChanged();
            }
        }
        private global::System.String _No_Telepon_Karyawan;
        partial void OnNo_Telepon_KaryawanChanging(global::System.String value);
        partial void OnNo_Telepon_KaryawanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email_Karyawan
        {
            get
            {
                return _Email_Karyawan;
            }
            set
            {
                OnEmail_KaryawanChanging(value);
                ReportPropertyChanging("Email_Karyawan");
                _Email_Karyawan = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email_Karyawan");
                OnEmail_KaryawanChanged();
            }
        }
        private global::System.String _Email_Karyawan;
        partial void OnEmail_KaryawanChanging(global::System.String value);
        partial void OnEmail_KaryawanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Alamat_Karyawan
        {
            get
            {
                return _Alamat_Karyawan;
            }
            set
            {
                OnAlamat_KaryawanChanging(value);
                ReportPropertyChanging("Alamat_Karyawan");
                _Alamat_Karyawan = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Alamat_Karyawan");
                OnAlamat_KaryawanChanged();
            }
        }
        private global::System.String _Alamat_Karyawan;
        partial void OnAlamat_KaryawanChanging(global::System.String value);
        partial void OnAlamat_KaryawanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Kota_Karyawan
        {
            get
            {
                return _Kota_Karyawan;
            }
            set
            {
                OnKota_KaryawanChanging(value);
                ReportPropertyChanging("Kota_Karyawan");
                _Kota_Karyawan = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Kota_Karyawan");
                OnKota_KaryawanChanged();
            }
        }
        private global::System.String _Kota_Karyawan;
        partial void OnKota_KaryawanChanging(global::System.String value);
        partial void OnKota_KaryawanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Jabatan
        {
            get
            {
                return _Jabatan;
            }
            set
            {
                OnJabatanChanging(value);
                ReportPropertyChanging("Jabatan");
                _Jabatan = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Jabatan");
                OnJabatanChanged();
            }
        }
        private global::System.String _Jabatan;
        partial void OnJabatanChanging(global::System.String value);
        partial void OnJabatanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="databaseModel", Name="db_Pelanggan")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class db_Pelanggan : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new db_Pelanggan object.
        /// </summary>
        /// <param name="iD_Pelanggan">Initial value of the ID_Pelanggan property.</param>
        public static db_Pelanggan Createdb_Pelanggan(global::System.String iD_Pelanggan)
        {
            db_Pelanggan db_Pelanggan = new db_Pelanggan();
            db_Pelanggan.ID_Pelanggan = iD_Pelanggan;
            return db_Pelanggan;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID_Pelanggan
        {
            get
            {
                return _ID_Pelanggan;
            }
            set
            {
                if (_ID_Pelanggan != value)
                {
                    OnID_PelangganChanging(value);
                    ReportPropertyChanging("ID_Pelanggan");
                    _ID_Pelanggan = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ID_Pelanggan");
                    OnID_PelangganChanged();
                }
            }
        }
        private global::System.String _ID_Pelanggan;
        partial void OnID_PelangganChanging(global::System.String value);
        partial void OnID_PelangganChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nama_Pelanggan
        {
            get
            {
                return _Nama_Pelanggan;
            }
            set
            {
                OnNama_PelangganChanging(value);
                ReportPropertyChanging("Nama_Pelanggan");
                _Nama_Pelanggan = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nama_Pelanggan");
                OnNama_PelangganChanged();
            }
        }
        private global::System.String _Nama_Pelanggan;
        partial void OnNama_PelangganChanging(global::System.String value);
        partial void OnNama_PelangganChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Jenis_Kelamin_Pelanggan
        {
            get
            {
                return _Jenis_Kelamin_Pelanggan;
            }
            set
            {
                OnJenis_Kelamin_PelangganChanging(value);
                ReportPropertyChanging("Jenis_Kelamin_Pelanggan");
                _Jenis_Kelamin_Pelanggan = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Jenis_Kelamin_Pelanggan");
                OnJenis_Kelamin_PelangganChanged();
            }
        }
        private global::System.String _Jenis_Kelamin_Pelanggan;
        partial void OnJenis_Kelamin_PelangganChanging(global::System.String value);
        partial void OnJenis_Kelamin_PelangganChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String No_Telepon_Pelanggan
        {
            get
            {
                return _No_Telepon_Pelanggan;
            }
            set
            {
                OnNo_Telepon_PelangganChanging(value);
                ReportPropertyChanging("No_Telepon_Pelanggan");
                _No_Telepon_Pelanggan = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("No_Telepon_Pelanggan");
                OnNo_Telepon_PelangganChanged();
            }
        }
        private global::System.String _No_Telepon_Pelanggan;
        partial void OnNo_Telepon_PelangganChanging(global::System.String value);
        partial void OnNo_Telepon_PelangganChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email_Pelanggan
        {
            get
            {
                return _Email_Pelanggan;
            }
            set
            {
                OnEmail_PelangganChanging(value);
                ReportPropertyChanging("Email_Pelanggan");
                _Email_Pelanggan = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email_Pelanggan");
                OnEmail_PelangganChanged();
            }
        }
        private global::System.String _Email_Pelanggan;
        partial void OnEmail_PelangganChanging(global::System.String value);
        partial void OnEmail_PelangganChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Alamat_Pelanggan
        {
            get
            {
                return _Alamat_Pelanggan;
            }
            set
            {
                OnAlamat_PelangganChanging(value);
                ReportPropertyChanging("Alamat_Pelanggan");
                _Alamat_Pelanggan = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Alamat_Pelanggan");
                OnAlamat_PelangganChanged();
            }
        }
        private global::System.String _Alamat_Pelanggan;
        partial void OnAlamat_PelangganChanging(global::System.String value);
        partial void OnAlamat_PelangganChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Kota_Pelanggan
        {
            get
            {
                return _Kota_Pelanggan;
            }
            set
            {
                OnKota_PelangganChanging(value);
                ReportPropertyChanging("Kota_Pelanggan");
                _Kota_Pelanggan = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Kota_Pelanggan");
                OnKota_PelangganChanged();
            }
        }
        private global::System.String _Kota_Pelanggan;
        partial void OnKota_PelangganChanging(global::System.String value);
        partial void OnKota_PelangganChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Count
        {
            get
            {
                return _Count;
            }
            set
            {
                OnCountChanging(value);
                ReportPropertyChanging("Count");
                _Count = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Count");
                OnCountChanged();
            }
        }
        private Nullable<global::System.Int32> _Count;
        partial void OnCountChanging(Nullable<global::System.Int32> value);
        partial void OnCountChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="databaseModel", Name="db_Retur_Pembelian")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class db_Retur_Pembelian : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new db_Retur_Pembelian object.
        /// </summary>
        /// <param name="no_Retur_Pembelian">Initial value of the No_Retur_Pembelian property.</param>
        public static db_Retur_Pembelian Createdb_Retur_Pembelian(global::System.String no_Retur_Pembelian)
        {
            db_Retur_Pembelian db_Retur_Pembelian = new db_Retur_Pembelian();
            db_Retur_Pembelian.No_Retur_Pembelian = no_Retur_Pembelian;
            return db_Retur_Pembelian;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String No_Retur_Pembelian
        {
            get
            {
                return _No_Retur_Pembelian;
            }
            set
            {
                if (_No_Retur_Pembelian != value)
                {
                    OnNo_Retur_PembelianChanging(value);
                    ReportPropertyChanging("No_Retur_Pembelian");
                    _No_Retur_Pembelian = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("No_Retur_Pembelian");
                    OnNo_Retur_PembelianChanged();
                }
            }
        }
        private global::System.String _No_Retur_Pembelian;
        partial void OnNo_Retur_PembelianChanging(global::System.String value);
        partial void OnNo_Retur_PembelianChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String No_Faktur_Pemesanan
        {
            get
            {
                return _No_Faktur_Pemesanan;
            }
            set
            {
                OnNo_Faktur_PemesananChanging(value);
                ReportPropertyChanging("No_Faktur_Pemesanan");
                _No_Faktur_Pemesanan = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("No_Faktur_Pemesanan");
                OnNo_Faktur_PemesananChanged();
            }
        }
        private global::System.String _No_Faktur_Pemesanan;
        partial void OnNo_Faktur_PemesananChanging(global::System.String value);
        partial void OnNo_Faktur_PemesananChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String No_Retur_Penjualan
        {
            get
            {
                return _No_Retur_Penjualan;
            }
            set
            {
                OnNo_Retur_PenjualanChanging(value);
                ReportPropertyChanging("No_Retur_Penjualan");
                _No_Retur_Penjualan = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("No_Retur_Penjualan");
                OnNo_Retur_PenjualanChanged();
            }
        }
        private global::System.String _No_Retur_Penjualan;
        partial void OnNo_Retur_PenjualanChanging(global::System.String value);
        partial void OnNo_Retur_PenjualanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tanggal
        {
            get
            {
                return _Tanggal;
            }
            set
            {
                OnTanggalChanging(value);
                ReportPropertyChanging("Tanggal");
                _Tanggal = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tanggal");
                OnTanggalChanged();
            }
        }
        private global::System.String _Tanggal;
        partial void OnTanggalChanging(global::System.String value);
        partial void OnTanggalChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="databaseModel", Name="db_Retur_Penjualan")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class db_Retur_Penjualan : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new db_Retur_Penjualan object.
        /// </summary>
        /// <param name="no_Retur_Penjualan">Initial value of the No_Retur_Penjualan property.</param>
        public static db_Retur_Penjualan Createdb_Retur_Penjualan(global::System.String no_Retur_Penjualan)
        {
            db_Retur_Penjualan db_Retur_Penjualan = new db_Retur_Penjualan();
            db_Retur_Penjualan.No_Retur_Penjualan = no_Retur_Penjualan;
            return db_Retur_Penjualan;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String No_Retur_Penjualan
        {
            get
            {
                return _No_Retur_Penjualan;
            }
            set
            {
                if (_No_Retur_Penjualan != value)
                {
                    OnNo_Retur_PenjualanChanging(value);
                    ReportPropertyChanging("No_Retur_Penjualan");
                    _No_Retur_Penjualan = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("No_Retur_Penjualan");
                    OnNo_Retur_PenjualanChanged();
                }
            }
        }
        private global::System.String _No_Retur_Penjualan;
        partial void OnNo_Retur_PenjualanChanging(global::System.String value);
        partial void OnNo_Retur_PenjualanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String No_Form_Penjualan_Grosir
        {
            get
            {
                return _No_Form_Penjualan_Grosir;
            }
            set
            {
                OnNo_Form_Penjualan_GrosirChanging(value);
                ReportPropertyChanging("No_Form_Penjualan_Grosir");
                _No_Form_Penjualan_Grosir = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("No_Form_Penjualan_Grosir");
                OnNo_Form_Penjualan_GrosirChanged();
            }
        }
        private global::System.String _No_Form_Penjualan_Grosir;
        partial void OnNo_Form_Penjualan_GrosirChanging(global::System.String value);
        partial void OnNo_Form_Penjualan_GrosirChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tanggal
        {
            get
            {
                return _Tanggal;
            }
            set
            {
                OnTanggalChanging(value);
                ReportPropertyChanging("Tanggal");
                _Tanggal = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tanggal");
                OnTanggalChanged();
            }
        }
        private global::System.String _Tanggal;
        partial void OnTanggalChanging(global::System.String value);
        partial void OnTanggalChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="databaseModel", Name="db_Supplier")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class db_Supplier : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new db_Supplier object.
        /// </summary>
        /// <param name="iD_Supplier">Initial value of the ID_Supplier property.</param>
        public static db_Supplier Createdb_Supplier(global::System.String iD_Supplier)
        {
            db_Supplier db_Supplier = new db_Supplier();
            db_Supplier.ID_Supplier = iD_Supplier;
            return db_Supplier;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID_Supplier
        {
            get
            {
                return _ID_Supplier;
            }
            set
            {
                if (_ID_Supplier != value)
                {
                    OnID_SupplierChanging(value);
                    ReportPropertyChanging("ID_Supplier");
                    _ID_Supplier = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ID_Supplier");
                    OnID_SupplierChanged();
                }
            }
        }
        private global::System.String _ID_Supplier;
        partial void OnID_SupplierChanging(global::System.String value);
        partial void OnID_SupplierChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nama_Supplier
        {
            get
            {
                return _Nama_Supplier;
            }
            set
            {
                OnNama_SupplierChanging(value);
                ReportPropertyChanging("Nama_Supplier");
                _Nama_Supplier = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nama_Supplier");
                OnNama_SupplierChanged();
            }
        }
        private global::System.String _Nama_Supplier;
        partial void OnNama_SupplierChanging(global::System.String value);
        partial void OnNama_SupplierChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String No_Telepon_Supplier
        {
            get
            {
                return _No_Telepon_Supplier;
            }
            set
            {
                OnNo_Telepon_SupplierChanging(value);
                ReportPropertyChanging("No_Telepon_Supplier");
                _No_Telepon_Supplier = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("No_Telepon_Supplier");
                OnNo_Telepon_SupplierChanged();
            }
        }
        private global::System.String _No_Telepon_Supplier;
        partial void OnNo_Telepon_SupplierChanging(global::System.String value);
        partial void OnNo_Telepon_SupplierChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email_Supplier
        {
            get
            {
                return _Email_Supplier;
            }
            set
            {
                OnEmail_SupplierChanging(value);
                ReportPropertyChanging("Email_Supplier");
                _Email_Supplier = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email_Supplier");
                OnEmail_SupplierChanged();
            }
        }
        private global::System.String _Email_Supplier;
        partial void OnEmail_SupplierChanging(global::System.String value);
        partial void OnEmail_SupplierChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Alamat_Supplier
        {
            get
            {
                return _Alamat_Supplier;
            }
            set
            {
                OnAlamat_SupplierChanging(value);
                ReportPropertyChanging("Alamat_Supplier");
                _Alamat_Supplier = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Alamat_Supplier");
                OnAlamat_SupplierChanged();
            }
        }
        private global::System.String _Alamat_Supplier;
        partial void OnAlamat_SupplierChanging(global::System.String value);
        partial void OnAlamat_SupplierChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Kota_Supplier
        {
            get
            {
                return _Kota_Supplier;
            }
            set
            {
                OnKota_SupplierChanging(value);
                ReportPropertyChanging("Kota_Supplier");
                _Kota_Supplier = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Kota_Supplier");
                OnKota_SupplierChanged();
            }
        }
        private global::System.String _Kota_Supplier;
        partial void OnKota_SupplierChanging(global::System.String value);
        partial void OnKota_SupplierChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Kodepos
        {
            get
            {
                return _Kodepos;
            }
            set
            {
                OnKodeposChanging(value);
                ReportPropertyChanging("Kodepos");
                _Kodepos = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Kodepos");
                OnKodeposChanged();
            }
        }
        private Nullable<global::System.Int32> _Kodepos;
        partial void OnKodeposChanging(Nullable<global::System.Int32> value);
        partial void OnKodeposChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Lama_Kontrak
        {
            get
            {
                return _Lama_Kontrak;
            }
            set
            {
                OnLama_KontrakChanging(value);
                ReportPropertyChanging("Lama_Kontrak");
                _Lama_Kontrak = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Lama_Kontrak");
                OnLama_KontrakChanged();
            }
        }
        private Nullable<global::System.Int32> _Lama_Kontrak;
        partial void OnLama_KontrakChanging(Nullable<global::System.Int32> value);
        partial void OnLama_KontrakChanged();

        #endregion

    
    }

    #endregion

    
}
